spring:
  application:
    name: security-all

  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true